"""
Website Builder skill for JARVIS.
Generates HTML pages and simple static websites.
"""
import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)


async def execute(command: str, **kwargs) -> dict:
    commands = {
        "generate_html": cmd_generate_html,
        "create_site": cmd_create_site,
    }
    handler = commands.get(command)
    if not handler:
        return {"error": f"Unknown command: {command}"}
    try:
        return await handler(**kwargs)
    except Exception as e:
        return {"error": str(e)}


async def cmd_generate_html(description: str, output_path: str) -> dict:
    """Generate an HTML file based on description."""
    p = Path(output_path).resolve()
    p.parent.mkdir(parents=True, exist_ok=True)

    # Basic template generation based on keywords in the description
    desc_lower = description.lower()
    title = "JARVIS Generated Page"

    # Extract a title from description
    import re
    title_match = re.search(r'(?:called|named|titled)\s+["\']?([^"\']+)["\']?', description, re.IGNORECASE)
    if title_match:
        title = title_match.group(1)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', system-ui, sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #2563eb; margin-bottom: 1rem; }}
        p {{ margin-bottom: 1rem; }}
        .container {{ padding: 2rem; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{title}</h1>
        <p>Generated by JARVIS based on: {description}</p>
        <p>This is a starting template. Customize it further by asking JARVIS to make changes.</p>
    </div>
</body>
</html>"""

    with open(p, "w", encoding="utf-8") as f:
        f.write(html)

    return {"status": "created", "path": str(p), "size": len(html)}


async def cmd_create_site(project_name: str, output_dir: str, pages: list = None) -> dict:
    """Create a multi-page static website."""
    root = Path(output_dir) / project_name
    root.mkdir(parents=True, exist_ok=True)

    if not pages:
        pages = [
            {"name": "index", "title": "Home"},
            {"name": "about", "title": "About"},
            {"name": "contact", "title": "Contact"},
        ]

    created = []
    nav_links = "\n".join(
        f'        <a href="{p["name"]}.html">{p["title"]}</a>'
        for p in pages
    )

    for page_data in pages:
        page_name = page_data["name"]
        page_title = page_data.get("title", page_name.capitalize())

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{page_title} - {project_name}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', system-ui, sans-serif; line-height: 1.6; color: #333; }}
        nav {{ background: #1e293b; padding: 1rem 2rem; }}
        nav a {{ color: white; text-decoration: none; margin-right: 1.5rem; font-weight: 500; }}
        nav a:hover {{ color: #60a5fa; }}
        .container {{ max-width: 900px; margin: 0 auto; padding: 2rem; }}
        h1 {{ color: #2563eb; margin-bottom: 1rem; }}
        footer {{ text-align: center; padding: 2rem; color: #666; font-size: 0.9rem; }}
    </style>
</head>
<body>
    <nav>
        {nav_links}
    </nav>
    <div class="container">
        <h1>{page_title}</h1>
        <p>This is the {page_title} page of {project_name}. Generated by JARVIS.</p>
    </div>
    <footer>
        <p>Generated by JARVIS &mdash; {project_name}</p>
    </footer>
</body>
</html>"""

        page_path = root / f"{page_name}.html"
        with open(page_path, "w", encoding="utf-8") as f:
            f.write(html)
        created.append(str(page_path))

    return {
        "status": "created",
        "project": str(root),
        "pages": len(created),
        "files": created,
    }
