"""
Model profiles - predefined model capabilities, context sizes, and routing preferences.
"""
MODEL_PROFILES = {
    "qwen3": {
        "capabilities": ["planning", "chat", "reasoning", "coding"],
        "context": 32768,
        "type": "general",
        "speed_rating": 4,
        "strengths": ["complex reasoning", "multi-step planning", "code generation"],
        "weaknesses": ["vision", "very long documents"],
    },
    "qwen2.5": {
        "capabilities": ["chat", "reasoning", "coding"],
        "context": 32768,
        "type": "general",
        "speed_rating": 4,
        "strengths": ["general chat", "reasoning", "code"],
        "weaknesses": ["vision"],
    },
    "deepseek-coder": {
        "capabilities": ["coding", "reasoning"],
        "context": 16384,
        "type": "coding",
        "speed_rating": 3,
        "strengths": ["code generation", "debugging", "code review"],
        "weaknesses": ["general chat", "creative writing"],
    },
    "deepseek-r1": {
        "capabilities": ["reasoning", "planning", "coding"],
        "context": 32768,
        "type": "reasoning",
        "speed_rating": 3,
        "strengths": ["deep reasoning", "math", "logic problems"],
        "weaknesses": ["speed", "simple tasks"],
    },
    "llama3.2": {
        "capabilities": ["chat", "reasoning"],
        "context": 8192,
        "type": "general",
        "speed_rating": 5,
        "strengths": ["fast responses", "general chat"],
        "weaknesses": ["complex coding", "long context"],
    },
    "phi3": {
        "capabilities": ["chat", "reasoning"],
        "context": 4096,
        "type": "lightweight",
        "speed_rating": 5,
        "strengths": ["speed", "low resource usage"],
        "weaknesses": ["complex tasks", "long context"],
    },
    "phi4": {
        "capabilities": ["chat", "reasoning", "coding"],
        "context": 16384,
        "type": "lightweight",
        "speed_rating": 4,
        "strengths": ["fast", "decent reasoning", "coding"],
        "weaknesses": ["vision"],
    },
    "llava": {
        "capabilities": ["vision", "chat"],
        "context": 4096,
        "type": "vision",
        "speed_rating": 2,
        "strengths": ["image understanding", "visual QA"],
        "weaknesses": ["speed", "text-only tasks"],
    },
    "qwen-vl": {
        "capabilities": ["vision", "chat", "reasoning"],
        "context": 8192,
        "type": "vision",
        "speed_rating": 3,
        "strengths": ["vision + reasoning", "detailed image analysis"],
        "weaknesses": ["pure speed"],
    },
    "nomic-embed-text": {
        "capabilities": ["embeddings"],
        "context": 8192,
        "type": "embedding",
        "speed_rating": 5,
        "strengths": ["text embeddings", "semantic search"],
        "weaknesses": ["text generation"],
    },
}

TASK_TO_CAPABILITY = {
    "chat": "chat",
    "conversation": "chat",
    "planning": "planning",
    "plan": "planning",
    "code": "coding",
    "coding": "coding",
    "debug": "coding",
    "vision": "vision",
    "image": "vision",
    "analyze_image": "vision",
    "reasoning": "reasoning",
    "reason": "reasoning",
    "math": "reasoning",
    "embedding": "embeddings",
    "search": "embeddings",
    "lightweight": "chat",
    "fast": "chat",
}
